# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer 
services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    App\Entity\Ingredient:
        autowire: true
    App\Repository\IngredientRepository:
        arguments:
            $class: 'App\Entity\Ingredient'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EntityListener\:
        resource: '../src/EntityListener'
        tags:
            - { name: 'doctrine.orm.entity_listener' }
            
    # App\Entity\User\:
    #     resource: '../src/Entity/'
    #     autowire: true 
    # App\Repository\UserRepository:
    #     arguments:
    #         $class: 'App\Entity\User'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones